### ISSUE TITLE
How to  Build ClientAPI in Windows platform

### ISSUE THREAD

**Issue by kirubhakinect** [Samsung/kv2streamer#2]
Hi,
    Now i am trying to execute Kv2Streamer source in Windows platform. Now i compiled Kinectv2server
suceesfully.but when i configuring the KinectClient side API.I am facing some issues.Also i am beginner in C++ . the following errors are i facing now:

  Error	30	error LNK2019: unresolved external symbol "public: __thiscall kv2s::KV2Client::~KV2Client(void)" (??1KV2Client@kv2s@@QAE@XZ) referenced in function "public: void * __thiscall kv2s::KV2Client::`scalar deleting destructor'(unsigned int)" (??_GKV2Client@kv2s@@QAEPAXI@Z)		KinectClient
Error	59	error LNK2019: unresolved external symbol "public: __thiscall kv2s::GstAppSrcPipeline::GstAppSrcPipeline(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,int)" (??0GstAppSrcPipeline@kv2s@@QAE@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z) referenced in function "public: __thiscall KV2ClientExample::KV2ClientExample(int,int,char const *)" (??0KV2ClientExample@@QAE@HHPBD@Z)	KinectClient
      

Error	67	error LNK2019: unresolved external symbol __imp__wglShareLists@8 referenced in function __glfwCreateContext	 KinectClient
Error	66	error LNK2019: unresolved external symbol __imp__wglMakeCurrent@8 referenced in function __glfwPlatformMakeContextCurrent
..\KinectClient\KinectClient\glfw3.lib(wgl_context.obj)	KinectClient

**Comment by kvnwinata** [comment]
Hi kirubhakinect,

Could you tell me how exactly you're compiling the client side application? Are you compiling it on Linux using codelite?

Kevin

**Comment by kirubhakinect** [comment]
Hi Kevin.
      Currently i compiling clientSide application with Windows platform using VisualStudio2012

**Comment by kvnwinata** [comment]
Hi Kirubha,

It seems that it's unable to find the compiled cpp files for the kv2streamer library. Did you include all the cpp files on the client side library?

But before that, could you tell me why you're using the kv2streamer library if you plan to compile on Windows? The kv2streamer is meant to be used for someone has to develop on a linux machine. If you're planning to develop on Windows, I'd recommend using the Kinect SDK directly instead of using kv2streamer.

Kevin

**Comment by kirubhakinect** [comment]
hi 
   Thanks kevin. now i  successfully configured and compiled the Kinectv2client source in visual studio 2012. but i facing some runtime error. please help to resolve this errror
![untitled](https://cloud.githubusercontent.com/assets/4300012/8127881/d5a8270a-1117-11e5-9bad-ebd9948a14d1.png)

this is the error wen i run the source shows

**Comment by kvnwinata** [comment]
Hi kirubhakinect,

Could you tell me how you install gstreamer? Which version of gstreamer did you install? It seems that it's missing the rtpbin plugin.

Kevin

**Comment by kirubhakinect** [comment]
Hi Kevin,
       I have downloaded Gstreamer Msi from  http://gstreamer.freedesktop.org/data/pkg/windows/   link 
and i checked following versions 
      1. gstreamer-1.0-devel-x86-1.0.10.msi 
       2.gstreamer-1.0-devel-x86-1.5.1.msi
       3.boost_1_55_0

please guide me to run this application

**Comment by kvnwinata** [comment]
Hi kirubhakinect,

I see, you might be missing the one package: gstreamer-1.0-x86-[xxx].msi, that's probably why it can't find rtpbin. Could you try installing it and see if it works?

Kevin

**Comment by kirubhakinect** [comment]
Hi kevin.
   I checked with  following version but it still throws 
    gstreamer-1.0-devel-x86-1.4.0.msi
    gstreamer-1.0-x86-1.4.0.msi
   http://www.boost.org/users/history/version_1_56_0.html

Error:

(kv2server_application.exe:8668): GStreamer-CRITICAL **: gst_bin_get_by_name: as
sertion 'GST_IS_BIN (bin)' failed
rtpbin name=rtpbin_name latency=25 udpsrc port=61404 address=192.168.1.11 auto-m
ulticast=true multicast-iface=eth1 ! application/x-rtp, media=video, payload=96,
 clock-rate=90000, encoding-name=H264 ! rtpbin_name.recv_rtp_sink_0 rtpbin_name.
 ! rtph264depay ! avdec_h264 ! videoconvert ! video/x-raw, format=RGB, width=128
0, height=720 ! appsink qos=true name=appsink_name

*\* (kv2server_application.exe:8668): CRITICAL **: gst_app_sink_set_drop: asserti
on 'GST_IS_APP_SINK (appsink)' failed

*\* (kv2server_application.exe:8668): CRITICAL **: gst_app_sink_set_max_buffers:
assertion 'GST_IS_APP_SINK (appsink)' failed

*\* (kv2server_application.exe:8668): CRITICAL **: gst_app_sink_set_emit_signals:
 assertion 'GST_IS_APP_SINK (appsink)' failed

*\* (kv2server_application.exe:8668): CRITICAL **: gst_app_sink_set_callbacks: as
sertion 'GST_IS_APP_SINK (appsink)' failed

(kv2server_application.exe:8668): GStreamer-CRITICAL *_: gst_element_set_state:
assertion 'GST_IS_ELEMENT (element)' failed
Unable to set the pipeline to the playing state
(kv2server_application.exe:8668): GStreamer-CRITICAL *_: gst_object_unref: asser
tion 'object != NULL' failed
[ColorFrameStreamer] Listening to 192.168.1.11 at port 61404
[BodyFrameStreamer] Listening to 192.168.1.11 at port 61402
0:00:01.445156905  8668   009B91A0 ERROR           GST_PIPELINE grammar.y:687:pr
iv_gst_parse_yyparse: no element "rtpbin"
0:00:01.446159625  8668   009B91A0 ERROR           GST_PIPELINE grammar.y:687:pr
iv_gst_parse_yyparse: no element "udpsrc"
0:00:01.447077845  8668   009B91A0 ERROR           GST_PIPELINE grammar.y:870:pr
iv_gst_parse_yyparse: link has no source [sink=rtpbin_name@00000000]
0:00:01.447828089  8668   009B91A0 ERROR           GST_PIPELINE grammar.y:687:pr
iv_gst_parse_yyparse: no element "rtpgstdepay"
0:00:01.448485964  8668   009B91A0 ERROR           GST_PIPELINE grammar.y:772:pr
iv_gst_parse_yyparse: link has no sink [source=rtpbin_name@00000000]
0:00:01.449207813  8668   009B91A0 ERROR           GST_PIPELINE grammar.y:687:pr
iv_gst_parse_yyparse: no element "pngdec"
0:00:01.462246600  8668   009B91A0 ERROR           GST_PIPELINE grammar.y:772:pr
iv_gst_parse_yyparse: link has no source [sink=@00000000]
0:00:01.463148056  8668   009B91A0 ERROR           GST_PIPELINE grammar.y:687:pr
iv_gst_parse_yyparse: no element "appsink"
0:00:01.464207909  8668   009B91A0 ERROR           GST_PIPELINE grammar.y:772:pr
iv_gst_parse_yyparse: link has no source [sink=@00000000]

(kv2server_application.exe:8668): GStreamer-CRITICAL **: gst_element_get_bus: as
sertion 'GST_IS_ELEMENT (element)' failed

(kv2server_application.exe:8668): GStreamer-CRITICAL **: gst_bus_add_watch_full:
 assertion 'GST_IS_BUS (bus)' failed

(kv2server_application.exe:8668): GStreamer-CRITICAL **: gst_bin_get_by_name: as
sertion 'GST_IS_BIN (bin)' failed
rtpbin name=rtpbin_name latency=50 udpsrc port=61406 address=192.168.1.11 auto-m
ulticast=true multicast-iface=eth1 ! application/x-rtp, media=application, paylo
ad=96, clock-rate=90000, encoding-name=X-GST, caps=aW1hZ2UvcG5nLGZyYW1lcmF0ZT0zM
C8xCg ! rtpbin_name.recv_rtp_sink_0 rtpbin_name. ! rtpgstdepay ! pngdec ! appsin
k qos=true name=appsink_name

*\* (kv2server_application.exe:8668): CRITICAL **: gst_app_sink_set_drop: asserti
on 'GST_IS_APP_SINK (appsink)' failed

*\* (kv2server_application.exe:8668): CRITICAL **: gst_app_sink_set_max_buffers:
assertion 'GST_IS_APP_SINK (appsink)' failed

*\* (kv2server_application.exe:8668): CRITICAL **: gst_app_sink_set_emit_signals:
 assertion 'GST_IS_APP_SINK (appsink)' failed

*\* (kv2server_application.exe:8668): CRITICAL **: gst_app_sink_set_callbacks: as
sertion 'GST_IS_APP_SINK (appsink)' failed

(kv2server_application.exe:8668): GStreamer-CRITICAL *_: gst_element_set_state:
assertion 'GST_IS_ELEMENT (element)' failed
Unable to set the pipeline to the playing state
(kv2server_application.exe:8668): GStreamer-CRITICAL *_: gst_object_unref: asser
tion 'object != NULL' failed
[DepthFrameStreamer] Listening to 192.168.1.11 at port 61406
0:00:01.511556088  8668   009B91A0 ERROR           GST_PIPELINE grammar.y:687:pr
iv_gst_parse_yyparse: no element "rtpbin"
0:00:01.512216358  8668   009B91A0 ERROR           GST_PIPELINE grammar.y:687:pr
iv_gst_parse_yyparse: no element "udpsrc"
0:00:01.512856785  8668   009B91A0 ERROR           GST_PIPELINE grammar.y:870:pr
iv_gst_parse_yyparse: link has no source [sink=rtpbin_name@00000000]
0:00:01.513595055  8668   009B91A0 ERROR           GST_PIPELINE grammar.y:687:pr
iv_gst_parse_yyparse: no element "rtph264depay"
0:00:01.514218720  8668   009B91A0 ERROR           GST_PIPELINE grammar.y:772:pr
iv_gst_parse_yyparse: link has no sink [source=rtpbin_name@00000000]
0:00:01.528247569  8668   009B91A0 ERROR           GST_PIPELINE grammar.y:687:pr
iv_gst_parse_yyparse: no element "avdec_h264"
0:00:01.528932470  8668   009B91A0 ERROR           GST_PIPELINE grammar.y:772:pr
iv_gst_parse_yyparse: link has no source [sink=@00000000]
0:00:01.529631056  8668   009B91A0 ERROR           GST_PIPELINE grammar.y:687:pr
iv_gst_parse_yyparse: no element "videoconvert"
0:00:01.539870026  8668   009B91A0 ERROR           GST_PIPELINE grammar.y:772:pr
iv_gst_parse_yyparse: link has no source [sink=@00000000]
0:00:01.540854957  8668   009B91A0 ERROR           GST_PIPELINE grammar.y:687:pr
iv_gst_parse_yyparse: no element "appsink"
0:00:01.542510078  8668   009B91A0 ERROR           GST_PIPELINE grammar.y:772:pr
iv_gst_parse_yyparse: link has no source [sink=@00000000]

(kv2server_application.exe:8668): GStreamer-CRITICAL **: gst_element_get_bus: as
sertion 'GST_IS_ELEMENT (element)' failed

(kv2server_application.exe:8668): GStreamer-CRITICAL **: gst_bus_add_watch_full:
 assertion 'GST_IS_BUS (bus)' failed

(kv2server_application.exe:8668): GStreamer-CRITICAL **: gst_bin_get_by_name: as
sertion 'GST_IS_BIN (bin)' failed
rtpbin name=rtpbin_name latency=50 udpsrc port=61408 address=192.168.1.11 auto-m
ulticast=true multicast-iface=eth1 ! application/x-rtp, media=video, payload=96,
 clock-rate=90000, encoding-name=H264 ! rtpbin_name.recv_rtp_sink_0 rtpbin_name.
 ! rtph264depay ! avdec_h264 ! videoconvert ! video/x-raw, format=GRAY8, width=5
12, height=424 ! appsink qos=true name=appsink_name

1.Why does this error comes?
2.How to solve this?

**Comment by kvnwinata** [comment]
It seems that gstreamer can't find rtpbin and the other elements. I'm not sure why this is because I've never seen this before, but my guess is that gstreamer is not properly installed. I would recommend reinstalling it and try using gst-inspect to see if the element is installed properly: http://docs.gstreamer.com/display/GstSDK/Basic+tutorial+10%3A+GStreamer+tools

**Comment by kirubhakinect** [comment]
Thanks Kevin,I forgot to set environment variables to my gstreamer path.Now this error got cleared.But 
I am getting some runtime errors. actually i given IP address in following code of KV2Client application 
"client.reset(new KV2Client("192.168.1.11", "eth0"));" If i give like this it throws network interface error.
please tell me what i have to give in place of the "eth0" in the above code.

**Comment by kvnwinata** [comment]
Great to hear that the errors are cleared!

Could you give me the full error message that you're getting?

Are you running the client on the same computer as the server or on a separate computer?
Also, kv2streamer uses multicast since the server is meant to multicast to many clients so it needs a multicast IP address (a specific range): https://en.wikipedia.org/wiki/IP_multicast

**Comment by kirubhakinect** [comment]
Hi Kevin,
          Thank you so much,Because now i am successfully executed.Kv2 client source  in Windows platform.previously i did mistake in setting  up IP address. Instead of  setting multicast address i set static IP address. Now i corrected that mistake it works fine.Again Thanks a lot.

**Comment by kvnwinata** [comment]
Hi kirubhakinect,

Great to hear that it's working now! 

-Kevin
